# Generated by Django 4.2.7 on 2025-09-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadproject',
            name='polyline_coordinates',
            field=models.JSONField(blank=True, help_text='Array of [lat, lng] coordinates for the road polyline', null=True),
        ),
    ]
