# Generated by Django 4.2.7 on 2025-09-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_roadproject_polyline_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadproject',
            name='polyline_color',
            field=models.CharField(default='#3388ff', help_text='Hex color code for the polyline (e.g., #ff0000)', max_length=7),
        ),
    ]
