# Generated by Django 4.2.7 on 2025-09-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_roadproject_polyline_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadsegment',
            name='end_latitude',
        ),
        migrations.RemoveField(
            model_name='roadsegment',
            name='end_longitude',
        ),
        migrations.RemoveField(
            model_name='roadsegment',
            name='start_latitude',
        ),
        migrations.RemoveField(
            model_name='roadsegment',
            name='start_longitude',
        ),
    ]
